export const about = {
  id: "about",
  lightBg: false,
  lightText: true,
  lightTextDesc: true,
  topLine: "Premium Bank",
  headline: "We provide you with the best",
  subtitle: "Insert subtitle here",
  description: "Insert short description here",
  buttonLabel: "Get Started Now",
  imgStart: false,
  img: require("../../images/Banking.svg").default,
  alt: "Car",
  dark: true,
  primary: true,
  darkText: false,
};

export const discover = {
  id: "discover",
  lightBg: true,
  lightText: false,
  lightTextDesc: false,
  topLine: "Insert topline",
  headline: "Insert headline here",
  subtitle: "Insert subtitle here",
  description: "Insert short description here",
  buttonLabel: "Button Text",
  imgStart: true,
  img: require("../../images/Discover.svg").default,
  alt: "Car",
  dark: false,
  primary: false,
  darkText: true,
};

export const signup = {
  id: "signup",
  lightBg: true,
  lightText: false,
  lightTextDesc: true,
  topLine: "Insert topline",
  headline: "Insert headline here",
  subtitle: "Insert subtitle here",
  description: "Insert short description here",
  buttonLabel: "Sign Up",
  imgStart: false,
  img: require("../../images/Join.svg").default,
  alt: "Car",
  dark: false,
  primary: false,
  darkText: true,
};
